# Generated by Django 2.2 on 2020-05-08 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_userprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user_one',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_one', to=settings.AUTH_USER_MODEL, verbose_name='user_one'),
        ),
        migrations.AddField(
            model_name='room',
            name='user_two',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_two', to=settings.AUTH_USER_MODEL, verbose_name='user_two'),
        ),
    ]
