# Generated by Django 2.2 on 2020-05-08 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20200508_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='user_one',
            field=models.ForeignKey(on_delete='default', related_name='user_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='user_two',
            field=models.ForeignKey(on_delete='default', related_name='user_two', to=settings.AUTH_USER_MODEL),
        ),
    ]
