# Generated by Django 2.2 on 2020-05-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20200508_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='arr_one',
            field=models.CharField(default='0', max_length=10000),
        ),
        migrations.AddField(
            model_name='room',
            name='arr_two',
            field=models.CharField(default='0', max_length=10000),
        ),
    ]
