# Generated by Django 2.2 on 2020-05-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20200512_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='step',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
