# Generated by Django 2.2 on 2020-05-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_userprofile_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_status',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
